/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unicv.aulas.projetobilheteria;
import com.unicv.aulas.projetobilheteria.classes.Estado;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.StringReader;
import java.net.HttpURLConnection;
import java.net.URI;
import java.net.URL;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.json.Json;
import javax.json.JsonArray;
import javax.json.JsonObject;
import javax.json.JsonReader;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pedro
 */
public class FormGerenciarEstados extends javax.swing.JFrame {

    private int id;
    private FormListaEstados formPai;
    
    public FormGerenciarEstados() {
        initComponents();
    }
     public void setConfiguracoes(int id, FormListaEstados pai) {
        this.id = id;
        this.formPai = pai;
    }

    public void carregarDados() {   
        
     // Configurando a requisição básica
    HttpClient client = HttpClient.newHttpClient();
    HttpRequest request = HttpRequest.newBuilder()
            .uri(URI.create("https://api-eventos-unicv.azurewebsites.net/api/estados"))
            .GET()
            .build();

    // declarando a lista de estados
    ArrayList<Estado> FormListaEstados = new ArrayList<Estado>();

    try {
        // Chamar a API para trazer os dados
        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

        // Verificar o código de retorno
        if (response.statusCode() == 200) {
            FormListaEstados = parseJsonArray(response.body());
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao listar estados");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    }
     private static ArrayList<Estado> parseJsonArray(String jsonArrayString) {
        ArrayList<Estado> listaEstados = new ArrayList<>();

        // Ler os dados do response
        JsonReader jsonReader = Json.createReader(new StringReader(jsonArrayString));
        JsonArray jsonArray = jsonReader.readArray();
        jsonReader.close();

        // Mapear cada objeto para a classe Estado
        for (int i = 0; i < jsonArray.size(); i++) {
            JsonObject json = jsonArray.getJsonObject(i);
            Estado objEstado = new Estado();
            objEstado.id = json.getInt("id");
            objEstado.nome = json.getString("name");
            objEstado.sigla = json.getString("acronym");

            // Adiciono o retorno na lista
            listaEstados.add(objEstado);
        }

        return listaEstados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        textSigla = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciar Estados");

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel1.setText("Id");

        jLabel2.setText("Sigla");

        jLabel3.setText("Nome");

        labelId.setText("00000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSigla)
                    .addComponent(textNome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 157, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // Pegando os valores digitados nos campos de texto
       int selecionado = this.id;
        String sigla = textSigla.getText();
        String nome = textNome.getText();

        // Verificando se a sigla e o nome estão vazios
        if (sigla.isEmpty() || nome.isEmpty()) {
            // Exibir mensagem de erro e não salvar
            JOptionPane.showMessageDialog(this, "A sigla e o nome não podem estar vazios.");
            return;
        }

        // Verificando se a sigla possui exatamente 2 caracteres e são letras
        if (sigla.length() != 2 || !sigla.matches("[a-zA-Z]+")) {
            // Exibir mensagem de erro e não salvar
            JOptionPane.showMessageDialog(this, "A sigla deve ter exatamente 2 letras.");
            return;
        }
        
        if (id == 0){
            adicionarEstado(sigla, nome);
            System.out.println("POST"); // chamar a API de POST
        }
        else{
            editarEstado(sigla,nome, selecionado);
            System.out.println("PUT"); // chamar a API de PUT
        }

        
        // Exibindo os valores no console
        System.out.println("Sigla: " + sigla + "\nNome: " + nome);
         
        
        // Enviando o estado para a API
       

        var form = new FormListaEstados();
        form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        form.setVisible(true);

        System.out.println("OnclickSalvar");
        this.dispose(); // Fechar
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:

        var form = new FormListaEstados();
        form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        form.setVisible(true);

        System.out.println("OnclickFechar");

        this.dispose(); // Fechar

    }//GEN-LAST:event_jButton1ActionPerformed

    public void adicionarEstado(String sigla, String nome) {
    try {
        // Construir o JSON com os dados do novo estado
        JsonObject estadoJson = Json.createObjectBuilder()
                .add("Name", nome)
                .add("Acronym", sigla)
                .build();

        // Criar o cliente HTTP
        HttpClient client = HttpClient.newHttpClient();

        // Construir a requisição HTTP PUT
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create("https://api-eventos-unicv.azurewebsites.net/api/estados"))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(estadoJson.toString()))
                .build();

        // Enviar a requisição e capturar a resposta
        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

        // Verificar o código de resposta
        if (response.statusCode() == 200) {
            // Estado adicionado com sucesso
            JOptionPane.showMessageDialog(this, "Estado adicionado com sucesso!");
        } else {
            // Exibir mensagem de erro se a resposta não for bem-sucedida
            JOptionPane.showMessageDialog(this, "Erro ao adicionar estado: " + response.body());
        }
    } catch (Exception e) {
        // Capturar e tratar exceções
        JOptionPane.showMessageDialog(this, "Erro ao comunicar com a API: " + e.getMessage());
        e.printStackTrace(); // Isso pode ser alterado para um tratamento mais adequado de exceções
    }
    }
    
     public void editarEstado(String sigla, String nome, int id) {
    try {
        // Construir o JSON com os dados do novo estado
        JsonObject estadoJson = Json.createObjectBuilder()
                .add("Name", nome)
                .add("Acronym", sigla)
                .build();

        // Criar o cliente HTTP
        HttpClient client = HttpClient.newHttpClient();

        // Construir a requisição HTTP PUT
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create("https://api-eventos-unicv.azurewebsites.net/api/estados?id=" + id))
                .header("Content-Type", "application/json")
                .PUT(HttpRequest.BodyPublishers.ofString(estadoJson.toString()))
                .build();

        // Enviar a requisição e capturar a resposta
        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

        // Verificar o código de resposta
        if (response.statusCode() == 200) {
            // Estado adicionado com sucesso
            JOptionPane.showMessageDialog(this, "Estado editado com sucesso!");
        } else {
            // Exibir mensagem de erro se a resposta não for bem-sucedida
            JOptionPane.showMessageDialog(this, "Erro ao editar estado: " + response.body());
        }
    } catch (Exception e) {
        // Capturar e tratar exceções
        JOptionPane.showMessageDialog(this, "Erro ao comunicar com a API: " + e.getMessage());
        e.printStackTrace(); // Isso pode ser alterado para um tratamento mais adequado de exceções
    }
    }


    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGerenciarEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGerenciarEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGerenciarEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGerenciarEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGerenciarEstados().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelId;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textSigla;
    // End of variables declaration//GEN-END:variables
}
